on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.8.2' 

    - name: Install dependencies
      run: npm install

    - name: Build Svelte app
      run: npm run deploy

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: build
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
